### PR TITLE
Fix issue #70 to expose a metric from a nested key

### PR DESCRIPTION
**Pull request by cvuillemez**

### CODE REVIEW

**Comment by cvuillemez** [comment]
Thanks, I amended the commit for DCO.
I 'll look for tests too.

**Comment by cvuillemez** [comment]
I wrote some tests. Is it sufficient ? (I'm not a Ruby developper, I didn't success to add a separate test, so I included it in "FULL_CONFIG").

**Comment by kazegusuri** [comment]
Thanks!

**Comment by cvuillemez** [comment]
Can you set a new release ?

**Comment by kazegusuri** [comment]
now we have v1.3.0 with this feature.

**Pull request merged**
